---
title: "Prevalence of hyperlipidemia in controlled and uncontrolled type‑2 diabetic patients"
type: "conference"
author: "Abul,H. Mohammad., Rahman,N.Farhan., Islam,N.Arafat., Hassan,M., Chondrow,P.Dev"
year: "2023"
publication: "36th BSM Annual Conference, Bangladesh Society of Microbiologists"
preprint: ""
doi: ""
materials: "publications/conference/ShahidMSB_BSM2023.pdf"
toc: false
categories:
  - Conference
---

## Abstract
Patients with type-2 diabetes mellitus (T2DM) are known to suffer from hyperlipidemia. How hyperlipidemia is associated with controlled and uncontrolled T2DM patients in Bangladesh remained to be addressed. In this cross-sectional study, 211 participants were enrolled who have been suffering from T2DM for more than 4 years from the northeastern part of Bangladesh. Controlled and uncontrolled patients were defined with their plasma glycated hemoglobin (HbA1c) levels.  Among them, 39% and 61% were in the diabetic-controlled and uncontrolled groups. Indeed, the diabetic uncontrolled group showed a higher frequency of hypercholesterolemia, hypertriglyceridemia, hyper LDL-cholesterolemia, and hypo HDLcholesterolemia compare to the diabetic controlled group. Lipid profiling analysis revealed significantly elevated (p<0.0001) levels of cholesterol, triglyceride, and low-density lipoprotein (LDL) in uncontrolled than the controlled group, while high-density lipoprotein (HDL) was significantly (p<0.0001) lower in uncontrolled diabetics patients. Interestingly, significantly (p<0.05) higher dyslipidemia was also observed in individuals with controlled diabetic population, who have been suffering from T2DM for more than 7 years. Therefore, these results highlight that not only the diabetic uncontrolled but also the controlled group patients have a high risk of developing hyperlipidemia after a certain period of diabetes. 
