---
title: "Identification of Potential Biomarkers for 2022 Mpox Virus Infection: A Transcriptomic Network Analysis and Machine Learning Approach"
type: "Journal Article"
author: "J.P. Debnath, K. Hossen, M.S. Khandaker, S.B. Sayed, Preonath Chondrow Dev*, S. Sarker*, T. Hossain*"
year: "2025"
publication: "Scientific Reports"
volume: "15"
article_number: "2922"
submission_date: "2024-09-20"
acceptance_date: "2024-11-19"
publication_date: "2025-01-23"
submission_id: "d89818e8-d058-4458-be49-a7df9916d775"
doi: "https://doi.org/10.1038/s41598-024-80519-7"
materials: "publications/journal/mpox_biomarkers.pdf"

corresponding_author: "Preonath Chondrow Dev"
contact_email: "email@example.com"
journal:
  name: "Scientific Reports"
  publisher: "Nature Publishing Group"
  link: "https://www.nature.com/srep/"
categories:
  - Virology
  - Bioinformatics
  - Machine Learning
  - Public Health
toc: false
---


## Abstract
Monkeypox virus (MPXV), a zoonotic pathogen, re-emerged in 2022 with the Clade IIb variant, raising global health concerns due to its unprecedented spread in non-endemic regions. Recent studies have shown that Clade IIb (2022 MPXV) is marked by unique genomic mutations and epidemiological behaviors, suggesting variations in host-virus interactions. This study aimed to identify the differentially expressed genes (DEGs) induced by the 2022 MPXV infection through comprehensive bioinformatics analyses of microarray and RNA-Seq datasets from post-infected cell types with different MPXV clades. Subsequently, gene expression network analyses pinpoint the key DEGs, followed by their candidate drug assessment using the Drug SIGnatures DataBase (DSigDB) and validation by multiple machine learning algorithms. Comparative differential gene expression (DGE) analysis revealed 798 DEGs exclusive to the 2022 MPXV invasion in the skin cell types (keratinocytes). Intriguingly, 13 key DEGs were identified across hubs and clusters, highlighting their aberrant expressions in cell cycle regulation, immune responses, and cancer pathways. Biomarker screening via Random Forest (RF) model (selected with PyCaret from multiple models) and validation through t-distributed stochastic neighbor embedding (t-SNE) algorithm, principal component analysis (PCA), and ROC curve analysis employing Logistic Regression and Random Forest, identified 6 key DEGs (TXNRD1, CCNB1, BUB1, CDC20, BUB1B, and CCNA2) as promising biomarkers (AUC > 0.7) for clade IIb infection. This study anticipates that further investigation and clinical trials will catalyze novel detection and therapeutic options to combat 2022 MPXV infection in humans.

**Keywords**: Mpox Virus, Biomarkers, Transcriptomics, Network Analysis, Machine Learning

## Results: